Issue #7 fix: explicitly exclude choose from bible match
A hacky fix, explicitly do not match requests starting with choose so that
choose can grab them instead and we don't end up with, e.g.
Lampstand: Choose 9:30 train or 11:30 train
producing
ERROR: No passage found for your query [ESV]